version: '3'

services:
    db:
        image: postgres:latest
        restart: always
        env_file:
            - ../.env
        ports:
            - 5432:5432
    db-admin:
        image: dpage/pgadmin4:latest
        restart: always
        env_file:
            - ../.env
        ports:
            - 8080:8080

